#!/usr/bin/env bash
# this script reads the contents of the /etc/passwd file and displays each user's username, user id, and home directory path.
while IFS=: read -r f1 f2 f3 f4 f5 f6 f7; do
	echo "$f1 $f3 $f6"
done < /etc/passwd
