#!/usr/bin/env bash
# This script will group visitors by IP address and HTTP status codes and number their occurences in list format from greatest to least from the apache-access.log file. 
awk '{count[$1 " " $9]++} END {for (key in count) print count[key], key}' apache-access.log | sort -nr
