#!/usr/bin/env bash
# This script will display numbers from 1 to 20. In iterations 4,9,and 17, these numbers will be followed by newline text stating respectively; "bad luck from China", Bad luck from Japan", and "bad luck from Italy".
i=1

while [[ $i -le 20 ]]; do
    if [[ $i -eq 4 ]]; then
        echo "$i 
bad luck from China"
    elif [[ $i -eq 9 ]]; then
        echo "$i
bad luck from Japan"
    elif [[ $i -eq 17 ]]; then
        echo "$i
bad luck from Italy"
    else 
	echo "$i"
    fi
    ((i += 1))
done
