#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes, displaying hours 0 to 12 and minitues within each hour from 1 to 59.
i=0
while [ $i -le 12 ]; do
        echo "Hour: $i"

        m=1
        while [ $m -le 59 ]; do
                echo "$m"
                ((m++));

        done

        ((i += 1));
done
