#!/usr/bin/env bash
# This script lists the names of files in the current directory displaying only the part of the name after the first dash.
for file in *; do 
	if [ -f "$file" ]; 
	then name=$(echo "$file" | cut -d'-' -f2-);
		echo "$name"; 
	fi;
done
