#!/usr/bin/env bash
# this script will confirm if the file 'school' exists and print information about it. If it does exist, the script will confirm if the file is empty or not, and if it is a regular file.
if [ -e school ]; then
	echo "school file exists";
	if [ -s school ]; then
		echo "school file is not empty";
	else 
		echo "school file is empty"
	fi
	if [ -f school ]; then
		echo "school is a regular file"
	fi;
else 
	echo "school file does not exist"
fi
